---
- name: Install Docker on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present

    - name: Update apt package index after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

- hosts: all
  become: true # Allows sudo privileges
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
    - name: Install essential packages
      apt:
        name:
          - curl
          - unzip
          - python3-pip # or python3-venv depending on your needs
      become: true
    - name: Download AWS CLI installer
      get_url:
        url: https://s3.amazonaws.com/aws-cli/awscli-linux-x86_64-py2.7.zip
        dest: /tmp/awscli.zip
    - name: Extract AWS CLI installer
      unarchive:
        copy: no
        dest: /tmp/
        path: /tmp/awscli.zip
    - name: Install AWS CLI
      shell: "python3 -m pip install --upgrade /tmp/awscli-linux-x86_64-py2.7/awscli-1.24.0-py2.7.egg"
      become: true # Required for shell tasks with sudo
    - name: Verify AWS CLI installation
      shell: "aws --version"
      register: awscli_version
      ignore_errors: yes
    - debug:
        msg: "AWS CLI Version: {{ awscli_version.stdout }}"

---
- name: Install Jenkins on Ubuntu
  hosts: jenkins
  become: yes

  tasks:

    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Java (Jenkins dependency)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins APT repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian binary/
        state: present

    - name: Update package list after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        enabled: yes
        state: started
  when: ansible_ec2_tag_Name == "dev-ec2-private-1"
